name: Spring Boot CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn clean package
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name : test secret
        run: |
          if [ -z "$MY_TEST_SECRET" ]; then
            echo "Secret missing"
            exit 1
          else
            echo "Secret successfully loaded!"
          fi
          env:
          MY_TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}